name: Build repository
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils

          rm addons.xml addons.xml.sha256 || true
          find . -type f -iname '*.zip' -delete

          echo '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' > addons.xml
          echo '<addons>' >> addons.xml
          find . -mindepth 1 -type f -name addon.xml -print0 | while IFS= read -r -d '' f; do
            xmllint --format "$f" | grep -v -F '<?xml ' >> addons.xml
          done
          echo '</addons>' >> addons.xml
          mv addons.xml addons.tmp.xml && xmllint --noblanks addons.tmp.xml > addons.xml && rm addons.tmp.xml
          sha256sum -b addons.xml > addons.xml.sha256

          find . -maxdepth 1 -type d -iname '*.*.*' -print0 | while IFS= read -r -d '' a; do
            version=$(xmllint --xpath 'string(/addon/@version)' $a/addon.xml)
            zip -9 -r $a/$a-$version.zip $a
          done
      - uses: actions/upload-artifact@v4
        with:
          name: repository
          path: |
            addons.xml
            addons.xml.sha256
            */*.zip
