name: Run tests
on: [push]
jobs:
  syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Validate XML files
        run: |
          find . -type f -iname '*.xml' -exec xmllint --noout -pedantic {} +
        continue-on-error: false
      - name: Compile with python
        run: |
          python -m compileall -q -r 2 .
        continue-on-error: false
